
import { Product, Language } from './types';

export const MOCK_PRODUCTS: Product[] = [
  // --- HẢI SẢN (Market Items) ---
  {
    id: 'f9',
    name: { vi: 'Cá mú tươi sống', en: 'Live Grouper', zh: '活石斑鱼' },
    price: { vi: 'Báo giá', en: 'Quote', zh: '报价' },
    description: { vi: 'Cá mú tươi sống đánh bắt tự nhiên, thịt ngọt, dai.', en: 'Fresh wild-caught live grouper.', zh: '天然捕获的新鲜活石斑鱼。' },
    cookingSuggestion: { vi: 'Hấp Hồng Kông với xì dầu.', en: 'Steamed Hong Kong style.', zh: '港式清蒸。' },
    image: 'https://i.ibb.co/Gv1GjGYD/c-m.jpg',
    category: { vi: 'Hải sản', en: 'Seafood', zh: '海鲜' },
    rating: 4.8,
    reviews: 52
  },
  {
    id: 'f10',
    name: { vi: 'Tôm sú tươi sống', en: 'Live Black Tiger Shrimp', zh: '活黑虎虾' },
    price: { vi: 'Báo giá', en: 'Quote', zh: '报价' },
    description: { vi: 'Tôm sú tươi sống, size lớn (10-15 con/kg).', en: 'Live black tiger shrimp, large size.', zh: '新鲜活黑虎虾。' },
    cookingSuggestion: { vi: 'Nướng muối ớt hoặc hấp nước dừa.', en: 'Grilled with salt and chili.', zh: '盐辣椒烧烤。' },
    image: 'https://i.ibb.co/XrppN1Qn/t-m-s.jpg',
    category: { vi: 'Hải sản', en: 'Seafood', zh: '海鲜' },
    rating: 4.8,
    reviews: 34
  },

  // --- 1. CHĂM SÓC CÁ NHÂN ---
  {
    id: 'pc1',
    name: { vi: 'Kem đánh răng Signal', en: 'Signal Toothpaste', zh: 'Signal 牙膏' },
    price: 450,
    description: { vi: 'Kem đánh răng bảo vệ nướu và làm trắng răng.', en: 'Toothpaste for gum protection and whitening.', zh: '牙膏，用于牙龈保护和美白。' },
    image: 'https://images.unsplash.com/photo-1559591937-e6b76a08ec8b?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Chăm Sóc Cá Nhân', en: 'Personal Care', zh: '个人护理' },
    rating: 4.5,
    reviews: 45,
    isShelfItem: true
  },
  {
    id: 'pc2',
    name: { vi: 'Dầu gội Sunsilk', en: 'Sunsilk Shampoo', zh: 'Sunsilk 洗发水' },
    price: 1200,
    description: { vi: 'Dầu gội mượt tóc, hương thơm quyến rũ.', en: 'Smooth hair shampoo with long-lasting scent.', zh: '柔滑洗发水，持久留香。' },
    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Chăm Sóc Cá Nhân', en: 'Personal Care', zh: '个人护理' },
    rating: 4.7,
    reviews: 120,
    isShelfItem: true
  },
  {
    id: 'pc3',
    name: { vi: 'Xà phòng Lux', en: 'Lux Soap', zh: 'Lux 香皂' },
    price: 180,
    description: { vi: 'Xà phòng dưỡng da hương nước hoa.', en: 'Perfumed skin nourishing soap.', zh: '香水滋养香皂。' },
    image: 'https://images.unsplash.com/photo-1600857062241-98e5dba7f214?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Chăm Sóc Cá Nhân', en: 'Personal Care', zh: '个人护理' },
    rating: 4.6,
    reviews: 98,
    isShelfItem: true
  },

  // --- 2. TẨY SẠCH – VỆ SINH ---
  {
    id: 'cl1',
    name: { vi: 'Bột giặt Sunlight', en: 'Sunlight Detergent', zh: 'Sunlight 洗衣粉' },
    price: 850,
    description: { vi: 'Sạch vết bẩn cứng đầu, hương thơm dịu nhẹ.', en: 'Cleans tough stains with a gentle scent.', zh: '清洁顽固污渍，香气柔和。' },
    image: 'https://images.unsplash.com/photo-1626806819282-2c1dc61a0e05?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Tẩy sạch – Vệ sinh', en: 'Cleaning & Hygiene', zh: '清洁卫生' },
    rating: 4.6,
    reviews: 88,
    isShelfItem: true
  },
  {
    id: 'cl2',
    name: { vi: 'Nước rửa bát Sunlight', en: 'Sunlight Dishwash', zh: 'Sunlight 洗洁精' },
    price: 350,
    description: { vi: 'Đánh bay dầu mỡ nhanh chóng.', en: 'Removes grease quickly.', zh: '快速去除油脂。' },
    image: 'https://images.unsplash.com/photo-1584622781564-1d9876a13d00?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Tẩy sạch – Vệ sinh', en: 'Cleaning & Hygiene', zh: '清洁卫生' },
    rating: 4.8,
    reviews: 210,
    isShelfItem: true
  },

  // --- 3. THỰC PHẨM KHÔ ---
  {
    id: 'df1',
    name: { vi: 'Mỳ Hảo Hảo', en: 'Hao Hao Noodles', zh: '好好方便面' },
    price: 350,
    description: { vi: 'Mỳ tôm chua cay quốc dân Việt Nam.', en: 'Vietnam\'s legendary sour and spicy noodles.', zh: '越南经典方便面。' },
    image: 'https://i.ibb.co/wNh3WQZv/hh.jpg',
    category: { vi: 'Thực Phẩm Khô', en: 'Dry Food', zh: '干货食品' },
    rating: 5.0,
    reviews: 500,
    isShelfItem: true
  },
  {
    id: 'df2',
    name: { vi: 'Gạo Basmati', en: 'Basmati Rice', zh: '印度香米' },
    price: 3200,
    description: { vi: 'Gạo dài, thơm, dẻo, đặc sản Sri Lanka.', en: 'Long, fragrant, premium rice from Sri Lanka.', zh: '来自斯里兰卡的长粒、芳香、优质大米。' },
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Thực Phẩm Khô', en: 'Dry Food', zh: '干货食品' },
    rating: 4.9,
    reviews: 145,
    isShelfItem: true
  },
  {
    id: 'df3',
    name: { vi: 'Dầu ăn Fortune', en: 'Fortune Oil', zh: 'Fortune 食用油' },
    price: 950,
    description: { vi: 'Dầu thực vật cao cấp.', en: 'Premium vegetable oil.', zh: '优质植物油。' },
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Thực Phẩm Khô', en: 'Dry Food', zh: '干货食品' },
    rating: 4.7,
    reviews: 64,
    isShelfItem: true
  },

  // --- 4. ĐỒ UỐNG ---
  {
    id: 'bv1',
    name: { vi: 'Bia Lion Strong', en: 'Lion Strong Beer', zh: '狮子烈性啤酒' },
    price: 650,
    description: { vi: 'Bia đặc sản Sri Lanka, hương vị mạnh mẽ.', en: 'Srilankan signature beer, bold flavor.', zh: '斯里兰卡招牌啤酒，口味浓郁。' },
    image: 'https://images.unsplash.com/photo-1550341914-98c085002e7a?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Đồ uống', en: 'Beverages', zh: '饮料' },
    rating: 4.7,
    reviews: 320,
    isShelfItem: true
  },
  {
    id: 'bv2',
    name: { vi: 'Nước trái cây EGB', en: 'EGB Fruit Juice', zh: 'EGB 果汁' },
    price: 450,
    description: { vi: 'Nước trái cây tự nhiên thơm ngon.', en: 'Natural and delicious fruit juice.', zh: '天然美味的果汁。' },
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Đồ uống', en: 'Beverages', zh: '饮料' },
    rating: 4.5,
    reviews: 76,
    isShelfItem: true
  },
  {
    id: 'bv3',
    name: { vi: 'Nước ngọt Ginger Beer', en: 'Ginger Beer', zh: '姜汁啤酒' },
    price: 320,
    description: { vi: 'Đặc sản Sri Lanka.', en: 'Sri Lankan specialty.', zh: '斯里兰卡特产。' },
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Đồ uống', en: 'Beverages', zh: '饮料' },
    rating: 4.9,
    reviews: 430,
    isShelfItem: true
  },

  // --- 5. BÁNH KẸO – ĂN VẶT ---
  {
    id: 'sk1',
    name: { vi: 'Snack Khoai Tây Lays', en: 'Lays Potato Chips', zh: '乐事薯片' },
    price: 450,
    description: { vi: 'Bánh snack khoai tây giòn rụm.', en: 'Crispy potato snacks.', zh: '脆脆的薯片。' },
    image: 'https://i.ibb.co/1gr4LF7/b-nh.jpg',
    category: { vi: 'Bánh Kẹo – Ăn Vặt', en: 'Snacks & Sweets', zh: '零食点心' },
    rating: 4.9,
    reviews: 310,
    isShelfItem: true
  },
  {
    id: 'sk2',
    name: { vi: 'Socola Kandos', en: 'Kandos Chocolate', zh: 'Kandos 巧克力' },
    price: 950,
    description: { vi: 'Socola sữa cao cấp Srilanka.', en: 'Premium Srilankan milk chocolate.', zh: '优质斯里兰卡牛奶巧克力。' },
    image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?q=80&w=200&auto=format&fit=crop',
    category: { vi: 'Bánh Kẹo – Ăn Vặt', en: 'Snacks & Sweets', zh: '零食点心' },
    rating: 4.8,
    reviews: 154,
    isShelfItem: true
  }
];

export const UI_STRINGS: Record<Language, any> = {
  vi: {
    welcome: 'Chào ngày mới!',
    question: 'Hôm nay bạn muốn ăn gì?',
    market: 'Srilanka Market',
    home: 'Chủ',
    search: 'Tìm',
    cart: 'Giỏ',
    me: 'Tôi',
    loginWithTelegram: 'Đăng nhập bằng Telegram',
    logout: 'Đăng xuất',
    searchPlaceholder: 'Tìm hải sản, rau củ...',
    aiAdviceTitle: 'Trợ lý FreshAI gợi ý',
    noItemsInCart: 'Giỏ hàng đang trống',
    goShop: 'Đi chợ ngay thôi!',
    billTotal: 'Tổng hóa đơn',
    checkout: 'Thanh Toán Ngay',
    deliveryTime: 'Giao hàng dự kiến: 30-45 phút',
    addToCart: 'Thêm vào giỏ',
    source: 'Nguồn gốc',
    freshness: 'Độ tươi',
    dailyFresh: 'Hàng ngày',
    vietnam: 'Srilanka / Việt Nam',
    language: 'Ngôn ngữ',
    profileTitle: 'Hồ sơ người dùng',
    reviews: 'đánh giá',
    todayOffer: 'Ưu đãi hôm nay',
    offerDesc: 'Giảm giá 20% đặc sản Srilanka',
    buyNow: 'Mua Ngay',
    unit: 'đơn vị',
    back: 'Quay lại',
    details: 'Chi tiết',
    cookingTitle: 'Gợi ý chế biến',
    contactInfo: 'Thông tin liên hệ',
    telegramPlaceholder: 'Tên Telegram hoặc SĐT...',
    confirmOrder: 'Xác nhận đặt hàng',
    orderSuccess: 'Thành công! Chúng tôi sẽ liên hệ với bạn sớm nhất.',
    payLaterNote: 'Lưu ý: Quý khách chọn hình thức "Thanh toán sau". Nhân viên của chúng tôi sẽ gọi điện xác nhận.',
    close: 'Đóng',
    customDelivery: 'Giao hàng theo yêu cầu',
    shareLocationInside: 'Gửi vị trí để shipper tìm đường nhanh hơn',
    shareLocationBtn: '📍 CHIA SẺ VỊ TRÍ HIỆN TẠI',
    locationShared: '✅ Vị trí đã được đính kèm',
    locating: 'Đang xác định vị trí...',
    locationError: 'Lỗi định vị. Vui lòng bật GPS!',
    citySelect: 'Chọn Thành phố của bạn',
    cityPlaceholder: 'Nhập thành phố...',
    contactLabel: 'Telegram / Số điện thoại',
    contactPlaceholder: 'Nhập Telegram hoặc SĐT liên hệ',
    needLabel: 'Bạn cần mua gì?',
    needPlaceholder: 'Ví dụ: Bia, Thuốc lá, Đồ ăn vặt...',
    freeDeliveryBtn: '🚀 GỬI YÊU CẦU GIAO HÀNG',
    payOnDelivery: 'THANH TOÁN KHI NHẬN HÀNG',
    paymentMethods: 'BANKING • TIỀN MẶT • CRYPTO',
    fastAndCheap: 'Nhanh chóng và Tiện lợi',
    cartItemsLabel: 'Sản phẩm trong giỏ',
    currencyConverter: 'Công cụ đổi tiền',
    convertFrom: 'Số tiền',
    convertTo: 'Chuyển đổi thành',
    shelfView: 'Kệ Hàng Tiêu Dùng'
  },
  en: {
    welcome: 'Good Morning!',
    question: 'What do you want to eat today?',
    market: 'Srilanka Market',
    home: 'Home',
    search: 'Search',
    cart: 'Cart',
    me: 'Profile',
    loginWithTelegram: 'Login with Telegram',
    logout: 'Logout',
    searchPlaceholder: 'Search seafood, veggies...',
    aiAdviceTitle: 'FreshAI Assistant Suggestion',
    noItemsInCart: 'Your cart is empty',
    goShop: 'Go Shopping Now!',
    billTotal: 'Bill Total',
    checkout: 'Checkout Now',
    deliveryTime: 'Est. Delivery: 30-45 mins',
    addToCart: 'Add to Cart',
    source: 'Origin',
    freshness: 'Freshness',
    dailyFresh: 'Daily Pick',
    vietnam: 'Sri Lanka / Vietnam',
    language: 'Language',
    profileTitle: 'User Profile',
    reviews: 'reviews',
    todayOffer: 'Today\'s Offer',
    offerDesc: '20% Off for Srilanka Special',
    buyNow: 'Buy Now',
    unit: 'unit',
    back: 'Back',
    details: 'Details',
    cookingTitle: 'Cooking Suggestion',
    contactInfo: 'Contact Information',
    telegramPlaceholder: 'Telegram username or Phone...',
    confirmOrder: 'Confirm Order',
    orderSuccess: 'Success! Our staff will contact you shortly.',
    payLaterNote: 'Note: You are choosing "Pay Later". Our staff will call to confirm.',
    close: 'Close',
    customDelivery: 'Custom Delivery Request',
    shareLocationInside: 'Share location for accurate delivery',
    shareLocationBtn: '📍 SHARE CURRENT LOCATION',
    locationShared: '✅ Location attached',
    locating: 'Locating...',
    locationError: 'Could not get location. Enable GPS!',
    citySelect: 'Choose your City',
    cityPlaceholder: 'Type city name...',
    contactLabel: 'Telegram / Phone number',
    contactPlaceholder: 'Enter Telegram or Phone number',
    needLabel: 'What do you need?',
    needPlaceholder: 'e.g., Drinks, snacks, items...',
    freeDeliveryBtn: '🚀 SEND DELIVERY REQUEST',
    payOnDelivery: 'PAY ON DELIVERY',
    paymentMethods: 'BANKING • CASH • CRYPTO',
    fastAndCheap: 'Faster and Better',
    cartItemsLabel: 'Items in Cart',
    currencyConverter: 'Currency Converter',
    convertFrom: 'Amount',
    convertTo: 'Converted to',
    shelfView: 'Consumer Goods Shelf'
  },
  zh: {
    welcome: '早上好！',
    question: '今天想吃点什么？',
    market: '斯里兰卡超市',
    home: '首页',
    search: '搜索',
    cart: '购物车',
    me: '我的',
    loginWithTelegram: '使用 Telegram 登录',
    logout: '退出登录',
    searchPlaceholder: '搜索新鲜海鲜、蔬菜...',
    aiAdviceTitle: 'FreshAI 智能助手建议',
    noItemsInCart: '购物车空空如也',
    goShop: '立即去逛逛',
    billTotal: '账单总计',
    checkout: '立即结算',
    deliveryTime: '预计送达时间: 30-45 分钟',
    addToCart: '加入购物车',
    source: '产地',
    freshness: '新鲜度',
    dailyFresh: '每日直采',
    vietnam: '斯里兰卡 / 越南',
    language: '语言',
    profileTitle: '美食达人',
    reviews: '条评价',
    todayOffer: '今日特惠',
    offerDesc: '斯里兰卡特产限时八折',
    buyNow: '立即购买',
    unit: '单位',
    back: '返回',
    details: '详情',
    cookingTitle: '烹饪建议',
    contactInfo: '联系信息',
    telegramPlaceholder: 'Telegram 账号或电话...',
    confirmOrder: '确认订单',
    orderSuccess: '下单成功！我们的工作人员将尽快联系您。',
    payLaterNote: '备注：您选择了“货到付款”。',
    close: '关闭',
    customDelivery: '按需送货',
    shareLocationInside: '共享位置以便精准配送',
    shareLocationBtn: '📍 共享当前位置',
    locationShared: '✅ 位置已附加',
    locating: '定位中...',
    locationError: '无法获取位置。',
    citySelect: '选择您的城市',
    cityPlaceholder: '输入城市...',
    contactLabel: 'Telegram / 电话号码',
    contactPlaceholder: '输入 Telegram 或电话号码',
    needLabel: '你需要什么？',
    needPlaceholder: '例如：饮料、零食、物品...',
    freeDeliveryBtn: '🚀 发送送货请求',
    payOnDelivery: '货到付款',
    paymentMethods: '银行转账 • 现金 • 加密货币',
    fastAndCheap: '更快捷，更方便',
    cartItemsLabel: '购物车内商品',
    currencyConverter: '汇率转换',
    convertFrom: '金额',
    convertTo: '转换结果',
    shelfView: '消费品货架'
  }
};
